/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
    prefix: "tw-",
    theme: {
    extend: {
        fontFamily: {
            'roboto': ['Roboto', 'sans-serif'],
        },
        colors: {
            'hawks-red': '#C8102E',
            'celtics-green': '#007A33',
            'nets-black': '#000000',
            'hornets-teal': '#00788C',
            'bulls-red': '#CE1141',
            'cavaliers-wine': '#860038',
            'cavaliers-gold': '#FDBB30',
            'mavericks-blue': '#00538C',
            'nuggets-blue': '#0E2240',
            'nuggets-yellow': '#FEC524',
            'pistons-red': '#C8102E',
            'pistons-royal': '#1D42BA',
            'warriors-blue': '#1D428A',
            'warriors-yellow': '#FFC72C',
            'rockets-red': '#CE1141',
            'pacers-yellow': '#FDBB30',
            'clippers-red': '#C8102E',
            'lakers-purple': '#552583',
            'lakers-gold': '#FDB927',
            'grizzlies-blue': '#5D76A9',
            'heat-red': '#98002E',
            'bucks-green': '#00471B',
            'timberwolves-blue': '#0C2340',
            'pelicans-gold': '#85714D',
            'knicks-blue': '#0072CE',
            'knicks-orange': '#FE5000',
            'thunder-blue': '#007AC1',
            'magic-blue': '#0077C0',
            '76ers-blue': '#0077C0',
            '76ers-red': '#ED174C',
            'suns-orange': '#E56020',
            'trailblazers-red': '#E03A3E',
            'kings-purple': '#5A2D81',
            'spurs-silver': '#C4CED4',
            'raptors-red': '#CE1141',
            'jazz-green': '#00471B',
            'wizards-blue': '#002B5C',
            'wizards-red': '#E31837',
        }
    },
  },
  plugins: [],
}

